language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
    
script:
  - cargo build --verbose
  - cargo build --verbose --features derive --examples
  - cargo test --verbose --features derive
